export const REQUEST_JOBS ='REQUEST_JOBS';
export const RECEIVE_JOBS ='RECEIVE_JOBS';
export const RECEIVE_JOBS_ERROR='RECEIVE_JOBS_ERROR';

export const SELECT_USER ='SELECT_USER';
export const REQUEST_USERDATA ='REQUEST_USERDATA';
export const RECEIVE_USERDATA ='RECEIVE_USERDATA';
export const RECEIVE_USERDATA_ERROR ='RECEIVE_USERDATA_ERROR';

export const SAVE_USERDATA ='SAVE_USERDATA';
export const SAVE_USERDATA_ERROR ='SAVE_USERDATA_ERROR';

export const SEARCH_MATCHING_JOBS = 'SEARCH_MATCHING_JOBS';
export const EDIT_USERDATA='EDIT_USERDATA'